services:
  db:
    image: mysql:8.0
    container_name: mysql_futbol
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: SQL_ROOT_PASSWORD
      MYSQL_DATABASE: DB_NAME
      MYSQL_USER: DB_USER
      MYSQL_PASSWORD: DB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  app:
    build: .
    container_name: php_futbol
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: DB_USER
      DB_PASSWORD: DB_PASSWORD
      DB_NAME: DB_NAME

volumes:
  db_data:
